version: "3.7"
services:
  php:
    build:
      context: .
    volumes:
      - ..:/workspace
    command: apache2-foreground
    ports:
      - 8080:80
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=laravel
      - MYSQL_DATABASE=laravel
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
